### ISSUE TITLE
Floor is arbitrary size and location (while grid seems to automatically adjust to the scene)

### ISSUE THREAD

**Issue by blundellj** [Smithsonian/dpo-voyager#7] opened 2020-02-06 15:59 UTC
Voyager version: v0.7.5
Scenes produced using play-to-voyager recipe, issue also shows up on content created from web-multi recipe and appears to be recipe independent

In the two examples below the grid seems to autosize correctly and is set just under the model, but the floor appears to be at an arbitrary size and height.

![image](https://user-images.githubusercontent.com/49207360/73950356-c80ad180-48c9-11ea-994a-b98e2de6be39.png)
mammoth - 341c96cd-f967-4540-8ed1-d3fc56d31f12

![image](https://user-images.githubusercontent.com/49207360/73950790-862e5b00-48ca-11ea-93e1-cfc60018db96.png)
1 Dollar, China, 1923 - 2b0560df-3f85-4c6a-a22f-7fe9f82d40b8

**Comment by framefactory** [comment] 2020-02-06 19:30
This is intended behavior. The floor is not automatically adjusted because it doesn't exist in Play scenes. Therefore it is not meant to show up when converting from Play to Voyager.

**Comment by gjcope** [comment] 2021-09-30 14:08
Fixed in #104

**Closed by gjcope** 2021-09-30 14:08 UTC
