### ISSUE TITLE
Videos not working on mobile

### ISSUE THREAD

**Issue by kgschoueri** [Smithsonian/dpo-voyager#306] opened 2024-09-18 08:46 UTC
For version 0.43.1, there are some bugs with videos embedded into articles when viewed on a mobile device (tested only on two iPhones). 

The mp4 stored within the Voyager Project is not working on the mobile version of the edition. It shows the play button but the player seems to be empty. It works as it should when viewed on a desktop (Chrome). This issue is not presented for videos embedded from Youtube or Vimeo for mobile devices (iPhone). 

The edition in which this error shows is here: https://viewer.acc.pure3d.eu/voyager-explorer-dev.html?root=models/53460aac36aa15966973df3af49793209eee2cf8/files/Documents/models/Kinora/&document=scene.svx.json 

Articles that have video media are: "Introduction", "Placing a Kinora reel", "Rotating a Kinora reel", "Viewing a Kinora reel" and "Replicating the Kinora viewer" and "Replicating the Kinora reel"

**Comment by gjcope** [comment] 2024-09-20 19:40
Hi @kgschoueri, I took a look at this and I believe this is an issue with the videos. Even when I tried loading them completely independently from Voyager, they did not work. Doing a little research, this seems to be a relatively common thing with iOS that has to do with the encoding of the video not being supported. Some threads on the issue suggest trying to re-encode with video software.

**Comment by gjcope** [comment] 2024-11-26 18:42
Tagging this as "not Voyager" and closing. If the issue is not addressed by the encoding suggestion above, feel free to reopen. Thanks!

**Closed by gjcope** 2024-11-26 18:42 UTC
Labels: not voyager
